/**
 * Author: Aisha Keller
 * Date: 07/08/2026
 * File: app.js
 * Description: Application setup. Autogenerated using Express Generator
 */

// require statements
const express = require('express');
const createError = require('http-errors');
const cookieParser = require('cookie-parser');
const logger = require('morgan');
const mongoose = require('mongoose');
const { notFoundHandler, errorHandler } = require('./error-handler');

// Importing the index router
const indexRouter = require('./routes/index');

// Variable declaration for the express app
let app = express();

const connectionString = process.env.MONGODB_URI || 'mongodb+srv://greenfieldANS:Password1@web450.6iupbaw.mongodb.net/?appName=WEB450';
const dbName = process.env.MONGODB_DB_NAME || 'inventoryDB';

if (process.env.NODE_ENV !== 'test') {
  mongoose.connect(connectionString, { dbName })
    .then(() => {
      console.log('Connected to MongoDB');
    })
    .catch((err) => {
      console.error(`MongoDB connection error: ${err}`);
    });
}

// CORS configuration
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*'); // This allows all origins
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS'); // Allowed request methods
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept'); // Allowed headers

  // Preflight requests never reach a route handler, so respond here with 204
  // instead of letting them fall through to the 404 handler.
  if (req.method === 'OPTIONS') {
    return res.sendStatus(204);
  }

  next();
});

// Express app configuration
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Routing configuration
app.use('/api', indexRouter);

// Use the error handling middleware
app.use(notFoundHandler);
app.use(errorHandler);

// Export the app
module.exports = app;
